spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/batch_test
    username: leeheefull
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always
    # batch.job.names: ${job.name:NONE}
    # Program arguments?? job.name? ???? ?? ??
    job:
      names: ${job.name:NONE}