spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_test
    username: root
    password:
  batch:
    jdbc:
      initialize-schema: always
    # batch.job.names: ${job.name:NONE}
    # Program arguments?? job.name? ???? ?? ??
    job:
      names: ${job.name:NONE}